// Generated by CoffeeScript 1.3.3
(function() {

  describe("MoodView", function() {
    beforeEach(function() {
      return this.moodView = App.MoodView.create();
    });
    it("should have default mood value", function() {
      return (expect(this.moodView.get('mood'))).toEqual('250');
    });
    it("should have default mood label value", function() {
      return (expect(this.moodView.get('moodLabel'))).toEqual('Ok');
    });
    return it("should have correct mood label when mood value changes", function() {
      this.moodView.set('mood', 120);
      (expect(this.moodView.get('moodLabel'))).toEqual('Bad');
      this.moodView.set('mood', 175);
      (expect(this.moodView.get('moodLabel'))).toEqual('Not so bad');
      this.moodView.set('mood', 240);
      (expect(this.moodView.get('moodLabel'))).toEqual('Ok');
      this.moodView.set('mood', 330);
      (expect(this.moodView.get('moodLabel'))).toEqual('Good');
      this.moodView.set('mood', 375);
      return (expect(this.moodView.get('moodLabel'))).toEqual('Great');
    });
  });

}).call(this);
